/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#475569",
        "surface-tint": "#2563eb",
        "on-tertiary-container": "#3730a3",
        "surface-variant": "#f1f5f9",
        "error": "#b91c1c",
        "surface-container-high": "#e2e8f0",
        "secondary": "#0284c7",
        "on-secondary-fixed": "#0f172a",
        "outline": "#cbd5e1",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#dbeafe",
        "surface-container": "#f8fafc",
        "on-secondary-fixed-variant": "#0284c7",
        "error-container": "#fee2e2",
        "primary-fixed": "#dbeafe",
        "surface-container-highest": "#cbd5e1",
        "inverse-surface": "#0f172a",
        "on-error-container": "#7f1d1d",
        "surface-container-low": "#f1f5f9",
        "secondary-container": "#e0f2fe",
        "outline-variant": "#e2e8f0",
        "on-primary-fixed": "#1e40af",
        "on-tertiary-fixed": "#1e1b4b",
        "secondary-fixed-dim": "#93c5fd",
        "on-surface": "#0f172a",
        "inverse-on-surface": "#f8fafc",
        "tertiary-container": "#e0e7ff",
        "secondary-fixed": "#e0f2fe",
        "surface": "#ffffff",
        "on-tertiary-fixed-variant": "#4f46e5",
        "on-background": "#0f172a",
        "primary": "#2563eb",
        "tertiary": "#4f46e5",
        "on-error": "#ffffff",
        "inverse-primary": "#2563eb",
        "on-secondary-container": "#0369a1",
        "on-tertiary": "#ffffff",
        "background": "#ffffff",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#2563eb",
        "on-primary-container": "#1e40af",
        "surface-bright": "#ffffff",
        "primary-fixed-dim": "#93c5fd",
        "tertiary-fixed": "#e0e7ff",
        "tertiary-fixed-dim": "#a5b4fc",
        "on-primary": "#ffffff",
        "surface-dim": "#f1f5f9"
      },
      spacing: {
        "gutter": "24px",
        "xl": "40px",
        "container-max": "1280px",
        "sm": "8px",
        "md": "16px",
        "3xl": "104px",
        "lg": "24px",
        "base": "4px",
        "xs": "4px",
        "2xl": "64px"
      },
      fontFamily: {
        "display-lg": ["Geist"],
        "display-sm": ["Geist"],
        "headline-lg-mobile": ["Geist"],
        "label-sm": ["JetBrains Mono"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["JetBrains Mono"],
        "headline-lg": ["Geist"]
      },
      fontSize: {
        "display-lg": ["64px", {"lineHeight": "72px", "letterSpacing": "-0.04em", "fontWeight": "700"}],
        "display-sm": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.03em", "fontWeight": "700"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
