import mongoose from 'mongoose';

const sessionSchema = new mongoose.Schema(
  {
    _id: {
      type: String, // Custom UUID or unique identifier generated by the tracker
      required: true
    },
    metadata: {
      os: String,
      browser: String,
      device: String,
      screenWidth: Number,
      screenHeight: Number
    }
  },
  {
    timestamps: true
  }
);

const Session = mongoose.model('Session', sessionSchema);
export default Session;
